### ISSUE TITLE
[NEEDED] Documentation Writers.

### ISSUE THREAD

**Issue by NTMNathan** [ntm-development/weeby-js#1]
As this is my first advanced API Wrapper i've made. I am in need for developers who are capable of implementing documentation for the `weeby-js` module.

**Comment by NTMNathan** [comment]
I am re-opening this issue again if developers would like to implement improved documentation for Weeby-JS.

Respond if you would like to participate.

**Comment by WiseDevHelper** [comment]
Could we make docs similar to [discord.js docs](https://discord.js.org)?

**Comment by NTMNathan** [comment]
That would be great!
