### ISSUE TITLE
[NEEDED] index.d.ts

### ISSUE THREAD

**Issue by NTMNathan** [ntm-development/weeby-js#2]
I've never done one of these before, despite seeing them in many NPM modules. This would be useful for TypeScript developers who would like to use `weeby-js` in TypeScript. Currently, this module is only fully supported for JavaScript.

**Comment by WiseDevHelper** [comment]
I'll be glad to help out on this and am planning to create a PR adding this soon.

**Comment by NTMNathan** [comment]
Thanks for the help!
